apiVersion: v1
kind: Pod
metadata:
  name: nextjs-app
spec:
  containers:
  - name: next-app
    image: ajeet999/next-app-gitops:f5b095795389a42a0b62aa85c0188000ff851a19
    ports:
    - containerPort: 80